import { useQuery } from '@tanstack/react-query'
import { TravelResponse } from '../../types/Travel.ts'

const mockedData: TravelResponse = {
  data: [
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
  ],
  totalPages: 3,
}

const useGetTravels = (page: number, pageSize: number) => {
  return useQuery<TravelResponse, Error>({
    queryKey: ['travels', page, pageSize],
    /*queryFn: () => getTravels(page, pageSize),*/
    queryFn: () =>
      new Promise((resolve) => {
        setTimeout(() => {
          const paginatedMockedData = {
            ...mockedData,
            data: mockedData.data.slice((page - 1) * pageSize, page * pageSize),
          }
          resolve(paginatedMockedData)
        }, 2500)
      }),
    staleTime: 5 * 60 * 1000,
  })
}
export default useGetTravels
