import { useQuery } from '@tanstack/react-query'
import { TravelResponse } from '../../types/Travel.ts'
/*import { getTravels } from '../api.ts'*/

const mockedData: TravelResponse = {
  data: [
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
    {
      CP: 'CP001',
      RazonSocial: 'Empresa 1',
      Cliente: 'Cliente A',
      Estado: 'En Proceso',
      Documentacion: 'Completa',
      Chofer: 'Juan Pérez',
      Carga: 'Carga general',
      Fecha: '2024-10-18',
      Patente: 'ABC123',
      Filial: 'Filial 1',
      Destino: 'Ciudad A',
      Proveedor: 'Proveedor 1',
    },
  ],
  totalPages: 3,
}

type SortingState = { id: string; desc: boolean }

const useGetTravels = (
  page: number,
  pageSize: number,
  sorting: SortingState[],
) => {
  /*const sortBy = sorting?.length > 0 ? sorting[0].id : undefined
  const sortOrder =
    sorting?.length > 0 ? (sorting[0].desc ? 'desc' : 'asc') : undefined*/

  return useQuery<TravelResponse, Error>({
    queryKey: ['travels', page, pageSize, sorting],
    /*queryFn: () => getTravels(page, pageSize, { sortBy, sortOrder }),*/
    queryFn: () =>
      new Promise((resolve) => {
        setTimeout(() => {
          const paginatedMockedData = {
            ...mockedData,
            data: mockedData.data.slice((page - 1) * pageSize, page * pageSize),
          }
          resolve(paginatedMockedData)
        }, 2500)
      }),
    staleTime: 5 * 60 * 1000,
  })
}
export default useGetTravels
